apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
data:
  mysql-server: mysql-app-server    # The name of mysql service
  mysql-database-name: springcondominio     # The name of the database used by the demo app
  mysql-user-username: myUser     # A new created user for the demo app 